import { GoogleGenAI, Type } from "@google/genai";
import type { SceneDescription } from '../types';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const SCRIPT_ANALYSIS_PROMPT = `
Analyze the following film or animation script and break it down into distinct, visually significant scenes.
For each scene, provide two things:
1.  A short, one-sentence 'scene_description' that summarizes the action or dialogue.
2.  A detailed 'image_prompt' for an AI image generator. This prompt should be highly descriptive, focusing on visual elements like character appearance, actions, setting, mood, lighting, and camera angle (e.g., 'close-up', 'wide shot'). Ensure the prompt is crafted to generate a compelling and contextually accurate storyboard frame.

The script is as follows:
---
`;

export async function parseScriptIntoScenes(script: string): Promise<SceneDescription[]> {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: SCRIPT_ANALYSIS_PROMPT + script,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              scene_description: {
                type: Type.STRING,
                description: 'A one-sentence summary of the scene.',
              },
              image_prompt: {
                type: Type.STRING,
                description: 'A detailed prompt for an AI image generator.',
              },
            },
            required: ["scene_description", "image_prompt"],
          },
        },
      },
    });

    const jsonText = response.text;
    const scenes = JSON.parse(jsonText) as SceneDescription[];
    return scenes;
  } catch (error) {
    console.error("Error parsing script:", error);
    throw new Error("Failed to analyze the script with Gemini.");
  }
}

export async function generateImageForScene(prompt: string): Promise<string> {
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '16:9',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image:", error);
    throw new Error(`Failed to generate image for prompt: "${prompt}"`);
  }
}
